[terminal.shell]
program = "zellij"

[general]
import = [
"~/.config/alacritty/catppuccin-mocha.toml"
]


[font]
normal = { family = "Iosevka Nerd Font", style = "Regular"}
bold = { family = "Iosevka Nerd Font", style = "Bold"}
size = 11

[window]
startup_mode = "Maximized"

[cursor]
style = {shape = "Beam", blinking = "On"}